"""Add Comment

Revision ID: 817b61530457
Revises: 8fb1c650b5d2
Create Date: 2026-01-29 22:45:27.413685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817b61530457'
down_revision = '8fb1c650b5d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_comment_todo_id', 'todo_item', ['todo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comment_todo_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'todo_item', ['todo_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
